.TH configtool 8 "3 Feb 2012" "J C Lawrence"
.SH NAME
configtool - Configuration management tool
.SH SYNOPSIS
.B configtool -a status
.P
.B configtool -a ACTION [-f] -m MODULE [-v] [-q]
.P
.B configtool -a ACTION [-f] -m MODULE [-q] [-w FILE] [-x FILE] [-c DIR]  [-d EXTENSION] [-l FILE] [-e EXTENSION] [-t HOST] [-r RELEASE]
.SH DESCRIPTION
Configtool implements centralised configuration management for installable entites.  The basic operation of configtool is to iterate across the list of configutation file templates provided for a module and to generate a localised confituation file for each of them by subsituting variables in the template with values defined in one or more topology files.
.P
The topology files are processed in alphabetical order, with the first value found accepted with subsequent files not searched.  Within a given topology file, the following recursive algorithm is used to searcha a variable's value.  The first match is taken:
.IP
Check variable[module][[host]][[[version]]]

Iteratively remove trailing characters from the right end of the version and recheck.

Check variable[module][[host]][[[version]]]

Iteratively removing trailing characters from the host and for each check for all permutations of iteratively removing characters from the version.

Check variable[module][[version]]

Iteratively remove trailing characters from the version.

Check variable[module][[host].

Iteratively remove trailing characters from the host.

Check variable[module].

Check variable[default][[host]].

Iteratively remove trailing characters from the host.

Check variable[default].
.PP
.SH BASIC OPTIONS
.TP
.B\--h
Display a brief list of possible arguments and help text.
.TP
.B\--a [check|sample|status|write], \--action=[check|sample|status|write]
.HP
.Bcheck - Compare the current configuration files with what is epxected from the template and current topology values
.HP
.Bsample - Generate sample configuration files (.../config_file.sample) using the current templates and topology files.
.HP
.Bstatus - Compare the configuations of all managed modules with the current topology and report if any diverge.
.HP
.Bwrite - Generate and install configuration files using the current templates and topology files.
.TP
.B\--f, \--force
Required by the 'write' action.
.B\--m, \--module=MODULE
Define the Application or module to process
.TP
.B\--r RELEASE, \--release=RELEASE
Required only if the application or module was not installed via an RPM lpackageor a different release version wants to be specified than was actually installed.  Alternative release (to that defined in the RPM database) to generate configuration files for.  (Defaults to the release listed int eh RPM database for $module)
.TP
.B\--b, \--nobackup
Do not make backups of the processed files
.TP
.B\--v, \--verbose
Output detailed operational reports to stdout
.TP
.B\--q, \--quiet
Supress default output of succsss/failure of operation (not the inverse of verbose)
.SH DEBUG OPTIONS
.TP
.B\--w FILE, \--localtool=FILE
Alternate location for configlocalise (defaults to configlocalise)
.TP
.B\--x FILE, \--execute=FILE
Alternate location for configmanage (defaults to configmanage)
.TP
.B\--c DIR, \--topodir=DIR
Alternate location for the topo directory (defaults to /etc/configtool/topo.d)
.TP
.B\--d EXTENSION, \--topoext=EXTENSION
Alternate extension to use for topo files (defaults to "topo")
.TP
.B\--l FILE, \--listfile=FILE
Alternate catalog of configuration files for module (defaults to /etc/configtool/modules.d/${module}.cfgs
.TP
.B\--e EXTENSION, \--extension=EXTENSION
Alternative file extension for configuration templates (defaults to "templ")
.TP
.B\--r RELEASE, \--release=RELEASE
Alternative release (to that defined in teh RPM database) to generate configuration files for.  (Defaults to the release listed int eh RPM database for $module)
.TP
.B\--t HOST, \--target=HOST
Alternate host to generate configuration files for (defaults to the FQDN of the localhost)
.SH EXAMPLES
.P
To check if the current confguration files for FOO are consistent with the current toplogy and templates:
.P
.B configtool -a check -m FOO
.P
To see what configuration files would be generated by the current topolgy and templates:
.P
.B configtool -a sample -m FOO
.P
To write|instantiate new configuration files using the current topolgy and templates:
.P
.B configtool -a write -f -m FOO
.P
To see what configuration files are managed for FOO:
.P
.B cat /etc/configtool/modules.d/FOO.cfgs
.SH FILES
/etc/configtool/topo.d/topo-internal.topo /etc/configtool/topo.d/topo-managed.topo /etc/configtool/topo.d/topo-production.topo /etcconfigtool/modules.d/{module}.cfgs /some/path/config_file.templ
.SH SEE ALSO
topo.d(5)
configtool(8)
configlocalise(8)
.SH DIAGNOSTICS
Return code of zero (0) on success, otherwise non-zero.  If quiet option is not provided, will output messages on failure to stderr.
.SH BUGS
This man page is weak sauce.
.SH AUTHOR
The configtool system was written by J C Lawrence <claw@kanga.nu>.
