all: configtool.8.gz configmanage.8.gz configlocalise.8.gz topo.d.5.gz

configtool.8.gz: configtool.8
	gzip -9 < configtool.8 > configtool.8.gz
configmanage.8.gz: configmanage.8
	gzip -9 < configmanage.8 > configmanage.8.gz
configlocalise.8.gz: configlocalise.8
	gzip -9 < configlocalise.8 > configlocalise.8.gz
topo.d.5.gz: topo.d.5
	gzip -9 < topo.d.5 > topo.d.5.gz
